spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tgBank
    username: pg
    password: pg
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  data:
    redis:
      host: localhost
      port: 6379
      password: my-password

server:
  port: 8080